### ISSUE TITLE
Verify consensus

### ISSUE THREAD

**Issue by bagavi** [ivicanikolicsg/OHIE#1]
I ran `quick_run.sh` script the output of different nodes (in `outputnode[x].txt` differs after running for 5 minutes. How to verify that all the nodes are reaching consensus and no node is lagging behind others?

**Comment by ivicanikolicsg** [comment]
Check the folder **_Hashes**.  It contains the blockchain with id 0 for all nodes. 
If you want to tweak the output of these files (change the id or print more chains), check MyServer.cpp starting from line 586

p.s. outputnode[x] may differ but only temporarily in [BLOCK HEADERS] and [LATENCY]. The remaing fields do not have to be the same
