### ISSUE TITLE
Parameters to obtain max throughput

### ISSUE THREAD

**Issue by bagavi** [ivicanikolicsg/OHIE#2]
**Machine**: aws c5d.4xlarge (16 cores, SSD).

**Question**: Under what setting can we obtain the maximum throughput (under parameters `SIGN_TRANSACTIONS= true`, `VERIFY_TRANSACTIONS=true` and `fake_transactions=false`)?

**Comment by ivicanikolicsg** [comment]
SING = false (meaning do not sign the transactions)
VERIFY=false (do not verify )
fake = true (use fake)
